[tool.commitizen]
name = "cz_conventional_commits"
version = "0.13.0"
tag_format = "v$version"
bump_message = "chore: bump version $current_version → $new_version"
version_files = [
    "src/version.sh:STOW_SH_VERSION",
]
